fig2,ax2 = plt.subplots(figsize=(20, 7))
ax2.plot(df.index/60, df['Boiler'],label = 'Boiler')
ax2.plot(df.index/60, df['Wash_Dryer'],label = 'Wash_Dryer')
ax2.plot(df.index/60, df['Dish_Washer'],label = 'Dish_Washer')
ax2.plot(df.index/60, df['Solar_Thermal_Pumping_Station'],label = 'Solar_Thermal_Pumping_Station')
ax2.plot(df.index/60, df['Laptop_Computer'],label = 'Laptop_Computer')
ax2.plot(df.index/60, df['Television'],label = 'Television')
ax2.plot(df.index/60, df['Home_Theater_PC'],label = 'Home_Theater_PC')
ax2.plot(df.index/60, df['Kettle'],label = 'Kettle')
ax2.plot(df.index/60, df['Toaster'],label = 'Toaster')
ax2.plot(df.index/60, df['Hair_Dryer'],label = 'Hair_Dryer')
ax2.plot(df.index/60, df['Hair_Straighteners'],label = 'Hair_Straighteners')
ax2.plot(df.index/60, df['Clothing_Iron'],label = 'Clothing_Iron')
ax2.plot(df.index/60, df['Oven'],label = 'Oven')
ax2.plot(df.index/60, df['Fan'],label = 'Fan')
ax2.plot(df.index/60, df['Washing_Machine'],label = 'Washing_Machine')
ax2.plot(df.index/60, df['EV'],label = 'EV')
ax2.plot(df.index/60, df['Refrigerator'],label = 'Refrigerator')
ax2.plot(df.index/60, df['Electric_Water_Heater'],label = 'Electric_Water_Heater')
ax2.plot(df.index/60, df['Washing_Machine_2'],label = 'Washing_Machine_2')
ax2.set_xlim(min(df.index/60),max(df.index/60))
#plt.ylim(0,max(df['Total_Power'])+10)
#ax2.set_ylim(0,200)
ax2.set_xlabel('Time (Hours)')
ax2.set_ylabel('Power (W)')
ax2.set_title('Load for a 24 hour period (Predicted)')
plt.grid()
plt.legend()
fig2.savefig(FILE_DIR_PATH/f'Figures/Optimized_Predicted_Load_Profile_for_HIL.png')
#plt.show()

